services:
    _defaults:
        public: true
        autowire: false
        autoconfigure: false

    HBM\BasicsBundle\Service\FormHelper:
        public: true
        arguments: ['@form.factory', '@router', '%hbm.basics.form%']

    HBM\BasicsBundle\Command\:
        resource: '../src/Command'
        tags:
            - { name: console.command }
